
import com.sun.glass.events.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rizwan
 */
public class DoctorGiveMedicineForm extends javax.swing.JFrame  {

    /**
     * Creates new form DoctorGiveMedicineForm
     */
    private int ID;
    Date date = new Date();
    public DoctorGiveMedicineForm() {
              initComponents();
          setDiseaseBox();
        this.setLocationRelativeTo(null);
        Patient p = new Patient();
        setPIDTxt();
               
    }
            public DoctorGiveMedicineForm(int ID){
         
            initComponents();
          setDiseaseBox();
        this.setLocationRelativeTo(null);
        Patient p = new Patient();
        setPIDTxt();
        PNameTxt.setText(p.getPName()); 
        GeneratePresButton.setEnabled(false);
        this.setLocationRelativeTo(null);
        DateTxt.setText(date.toString());
           UserIDTxt.setText(String.valueOf(ID));
           Doctor d=new Doctor();
          try {
           ResultSet rst;
          rst = d.getname(Integer.parseInt(UserIDTxt.getText()));
         String Name = rst.getString("DName");
          String Field = rst.getString("DField");
          UserNameTxt.setText(Name);
          DFieldTxt.setText(Field);
      } catch (SQLException ex) {
          
      }
           
       }

    public void setPIDTxt(){
 ResultSet rst;
        try {
            Receptionist rec = new Receptionist();
             rst = rec.GetCheckInPatientID();
              if(!rst.next()){
                 JOptionPane.showMessageDialog(null, "No More Patients On List");
              }
               else{
             do{
                PIDCombo.addItem(rst.getString("PID"));
                  } while(rst.next());
              }
        
        } 
        catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, ex);
        }
    }
    public void setDiseaseBox(){
        ResultSet rst;
        try{
            Medicine m = new Medicine();
            rst = m.select_Disease_Type();
            while(rst.next()){
                DiseaseCombo.addItem(rst.getString("DiseaseType"));
            }
            
        }
        catch(Exception e){
            
        }
    }
    public void setQuantityBox(){
        ResultSet rst;
            String MName = String.valueOf(MedicineCombo.getSelectedItem());
            Medicine m = new Medicine();
        try{
           
            rst = m.M_Quantity(MName);
            if(rst.next()){
               QuantityAvailableTxt.setText(rst.getString("Quantity") );
            }
        }catch(Exception e){
            
        }
    }
    public void setPriceBox(){
        ResultSet rst;
        String MName = String.valueOf(MedicineCombo.getSelectedItem());
        Medicine m = new Medicine();
        try{
            rst = m.M_Price(MName);
            if(rst.next()){
               int price = Integer.parseInt(rst.getString("MPrice"));
                UnitPriceTxt.setText( price+ " Rupees");
        
            }
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        PatientInfoButton = new javax.swing.JButton();
        SignOutButton = new javax.swing.JButton();
        UpcomingAppButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        QToGiveTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        MedicineCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        PNameTxt = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DiseaseCombo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        UnitPriceTxt = new javax.swing.JLabel();
        GeneratePresButton = new javax.swing.JButton();
        QuantityAvailableTxt = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TPriceTxt = new javax.swing.JLabel();
        CheckOutChk = new javax.swing.JCheckBox();
        AddButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MedicinesGiven = new javax.swing.JTextArea();
        PIDCombo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        BillNoTxt = new javax.swing.JLabel();
        DateTxt = new javax.swing.JLabel();
        Txt = new javax.swing.JLabel();
        UserIDTxt = new javax.swing.JLabel();
        UserNameTxt = new javax.swing.JLabel();
        DFieldTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255)));
        jPanel3.setLayout(null);

        jButton1.setText("Give Medicine");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(2, 96, 170, 39);

        PatientInfoButton.setText("Patient Information");
        PatientInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientInfoButtonActionPerformed(evt);
            }
        });
        jPanel3.add(PatientInfoButton);
        PatientInfoButton.setBounds(2, 148, 170, 39);

        SignOutButton.setText("Sign Out");
        SignOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignOutButtonActionPerformed(evt);
            }
        });
        jPanel3.add(SignOutButton);
        SignOutButton.setBounds(0, 210, 170, 39);

        UpcomingAppButton.setText("Upcoming Appointments");
        UpcomingAppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpcomingAppButtonActionPerformed(evt);
            }
        });
        jPanel3.add(UpcomingAppButton);
        UpcomingAppButton.setBounds(2, 46, 170, 39);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 90, 170, 440);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setLayout(null);

        QToGiveTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        QToGiveTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QToGiveTxtActionPerformed(evt);
            }
        });
        QToGiveTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                QToGiveTxtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                QToGiveTxtKeyTyped(evt);
            }
        });
        jPanel2.add(QToGiveTxt);
        QToGiveTxt.setBounds(230, 300, 180, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Patient ID");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(50, 20, 90, 30);

        MedicineCombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MedicineCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        MedicineCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicineComboActionPerformed(evt);
            }
        });
        jPanel2.add(MedicineCombo);
        MedicineCombo.setBounds(230, 180, 180, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Medicine");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 180, 90, 30);

        PNameTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PNameTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(PNameTxt);
        PNameTxt.setBounds(230, 100, 180, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Patient Name");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(50, 100, 120, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Disease");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(50, 140, 90, 30);

        DiseaseCombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DiseaseCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiseaseComboActionPerformed(evt);
            }
        });
        jPanel2.add(DiseaseCombo);
        DiseaseCombo.setBounds(230, 140, 180, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Quantity Available");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(50, 220, 130, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Unit Price");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(50, 260, 90, 30);

        UnitPriceTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UnitPriceTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(UnitPriceTxt);
        UnitPriceTxt.setBounds(230, 260, 180, 30);

        GeneratePresButton.setText("Generate Bill");
        GeneratePresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneratePresButtonActionPerformed(evt);
            }
        });
        jPanel2.add(GeneratePresButton);
        GeneratePresButton.setBounds(130, 380, 170, 40);

        QuantityAvailableTxt.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        QuantityAvailableTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(QuantityAvailableTxt);
        QuantityAvailableTxt.setBounds(230, 220, 180, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Quantity to Give");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(50, 300, 140, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Total Price");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(50, 340, 90, 30);

        TPriceTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TPriceTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(TPriceTxt);
        TPriceTxt.setBounds(230, 340, 180, 30);

        CheckOutChk.setBackground(new java.awt.Color(51, 255, 255));
        CheckOutChk.setText("Check Out");
        CheckOutChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutChkActionPerformed(evt);
            }
        });
        jPanel2.add(CheckOutChk);
        CheckOutChk.setBounds(20, 390, 100, 23);

        AddButton.setText("Add");
        AddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButtonMouseClicked(evt);
            }
        });
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        jPanel2.add(AddButton);
        AddButton.setBounds(420, 143, 70, 30);

        MedicinesGiven.setColumns(20);
        MedicinesGiven.setRows(5);
        jScrollPane1.setViewportView(MedicinesGiven);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(420, 180, 180, 110);

        PIDCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ID" }));
        PIDCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIDComboActionPerformed(evt);
            }
        });
        jPanel2.add(PIDCombo);
        PIDCombo.setBounds(230, 20, 180, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Bill Number");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(50, 60, 120, 30);

        BillNoTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BillNoTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(BillNoTxt);
        BillNoTxt.setBounds(230, 60, 180, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(170, 90, 670, 440);

        DateTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DateTxt.setForeground(new java.awt.Color(255, 255, 255));
        DateTxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        jPanel1.add(DateTxt);
        DateTxt.setBounds(560, 50, 260, 30);

        Txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Txt.setForeground(new java.awt.Color(255, 255, 255));
        Txt.setText("LOGIN AS");
        Txt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        jPanel1.add(Txt);
        Txt.setBounds(10, 10, 80, 30);

        UserIDTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UserIDTxt.setForeground(new java.awt.Color(255, 255, 255));
        UserIDTxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        jPanel1.add(UserIDTxt);
        UserIDTxt.setBounds(100, 10, 70, 30);

        UserNameTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UserNameTxt.setForeground(new java.awt.Color(255, 255, 255));
        UserNameTxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        jPanel1.add(UserNameTxt);
        UserNameTxt.setBounds(180, 10, 110, 30);

        DFieldTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DFieldTxt.setForeground(new java.awt.Color(255, 255, 255));
        DFieldTxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        jPanel1.add(DFieldTxt);
        DFieldTxt.setBounds(10, 50, 280, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignOutButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        LoginScreenForm login = new LoginScreenForm();
        JOptionPane.showMessageDialog(null, "Logged Out");
        login.setVisible(true);
    }//GEN-LAST:event_SignOutButtonActionPerformed

    private void PatientInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientInfoButtonActionPerformed
        // TODO add your handling code here:
        PatientVisitHistory info = new PatientVisitHistory(Integer.parseInt(UserIDTxt.getText()));
       
        info.setVisible(true);
    }//GEN-LAST:event_PatientInfoButtonActionPerformed

    private void UpcomingAppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpcomingAppButtonActionPerformed
        // TODO add your handling code here:
        DoctorUpcomingAppointmentsForm nb = new DoctorUpcomingAppointmentsForm();
        nb.setVisible(true);
    }//GEN-LAST:event_UpcomingAppButtonActionPerformed

    private void MedicineComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicineComboActionPerformed
        // TODO add your handling code here:
       
        setQuantityBox();
        setPriceBox();
        
       //MedicinesGiven.setText(String.valueOf(MedicineCombo.getSelectedItem())  + "\t "+ QToGiveTxt.getText());
        
    }//GEN-LAST:event_MedicineComboActionPerformed

    private void DiseaseComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiseaseComboActionPerformed
            MedicineCombo.removeAllItems();
        ResultSet rst;
         String disease = String.valueOf(DiseaseCombo.getSelectedItem());
    
            Medicine m = new Medicine();
            rst = m.select_Medicine_Name(disease);
             try {
                 while(rst.next()){
                     MedicineCombo.addItem(rst.getString("MName"));
 }
             } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
                
             }         // TODO add your handling code here:
       
    }//GEN-LAST:event_DiseaseComboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DoctorGiveMedicineForm give = new DoctorGiveMedicineForm(Integer.parseInt(UserIDTxt.getText()));
        this.setVisible(false);
        give.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void GeneratePresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneratePresButtonActionPerformed
        // TODO add your handling code here:
        int m_price = Integer.parseInt(TPriceTxt.getText());
        String s_med = MedicinesGiven.getText();
        String BNo = BillNoTxt.getText();
        Bill bill = new Bill(s_med, m_price);
        bill.UpdateBill(BNo);
                
                   
//        PrescriptionForm pre = new PrescriptionForm();
//        this.setVisible(false);
//        pre.setVisible(true);
        
        
    }//GEN-LAST:event_GeneratePresButtonActionPerformed

    private void QToGiveTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QToGiveTxtActionPerformed
        // TODO add your handling code here:
         
       
    }//GEN-LAST:event_QToGiveTxtActionPerformed

    private void QToGiveTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QToGiveTxtKeyPressed
        // TODO add your handling code here:

                
    }//GEN-LAST:event_QToGiveTxtKeyPressed

    private void QToGiveTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QToGiveTxtKeyTyped
        // TODO add your handling code here:
        
          char c = evt.getKeyChar();
        if (!( Character.isDigit(c) || (c==KeyEvent.VK_BACKSPACE) || (c== KeyEvent.VK_DELETE))){
            evt.consume();
        }
            ResultSet rst;
        String MName = String.valueOf(MedicineCombo.getSelectedItem());
        Medicine m = new Medicine();
        try{
            rst = m.M_Price(MName);
            if(rst.next()){
                int price = Integer.parseInt(rst.getString("MPrice"));
                int qTGive = Integer.parseInt(QToGiveTxt.getText());
                int qAvailable = Integer.parseInt(QuantityAvailableTxt.getText());
                    if(qTGive > qAvailable){
                        JOptionPane.showMessageDialog(null, qTGive + MName + " Are Not In Stock");
                        QToGiveTxt.setText("");
                        TPriceTxt.setText("");
                    }
                    else{
                         int TotalPrice = price * qTGive;
                        TPriceTxt.setText(String.valueOf(TotalPrice));
                    }
            }
            }catch(Exception e){
           
        }

    
    }//GEN-LAST:event_QToGiveTxtKeyTyped

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        ResultSet rst;
            String MName = String.valueOf(MedicineCombo.getSelectedItem());
            Medicine m = new Medicine();
            if(QToGiveTxt.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Enter Quantity To Give");
            }
            else{
                     try{
           
            rst = m.M_Quantity(MName);
            if(rst.next()){
               int quantity = Integer.parseInt(rst.getString("Quantity"));
               int Qtogive = Integer.parseInt(QToGiveTxt.getText());
               if(Qtogive>quantity){
                   JOptionPane.showMessageDialog(null,Qtogive + " "+ MName + " Are Not in the Stock");
                   TPriceTxt.setText("");
                  }
            else{
                   int updateQuantity = quantity-Qtogive;
                   QuantityAvailableTxt.setText(String.valueOf(updateQuantity) );
                   Medicine med = new Medicine();
                   med.M_Quantity(MName);
                   med.Update_M_Quantity(MName,Integer.parseInt(QuantityAvailableTxt.getText()));
                    String medicines = "\n" + String.valueOf(MedicineCombo.getSelectedItem())  + "\t "+ QToGiveTxt.getText();
                    MedicinesGiven.append(medicines); 
                   
                 }
            }
        }catch(Exception e){
            
        }
            }
  
    }//GEN-LAST:event_AddButtonActionPerformed

    private void AddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButtonMouseClicked
        // TODO add your handling code here:
      
      
    }//GEN-LAST:event_AddButtonMouseClicked

    private void CheckOutChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutChkActionPerformed
        // TODO add your handling code here:
           if(CheckOutChk.isSelected()){
             if(PIDCombo.getSelectedItem().equals("Select ID") || QToGiveTxt.getText().equals("") || MedicinesGiven.getText().equals("") )
        {
           JOptionPane.showMessageDialog(null, "Make Sure all Fields are Filled");
             CheckOutChk.setSelected(false);
             //GeneratePresButton.setEnabled(false);
            }
             else{
            try{
                GeneratePresButton.setEnabled(true);
               Receptionist rec = new Receptionist();
            int ID = Integer.parseInt(String.valueOf(PIDCombo.getSelectedItem()));
            String status = CheckOutChk.getText();
            rec.UpdateCheckInOut(ID,status);  
            Bill bill = new Bill();
            bill.UpdateCheckInOutBill(ID, status);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "CheckOut Error");
            }
        }
        }
    }//GEN-LAST:event_CheckOutChkActionPerformed

    private void PIDComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIDComboActionPerformed
        // TODO add your handling code here:
        ResultSet rst;
        if(PIDCombo.getSelectedItem().equals("Select ID")){
            PNameTxt.setText("");
        }
        else{
             try{
            Receptionist rec =  new Receptionist();
            int ID = Integer.parseInt(String.valueOf(PIDCombo.getSelectedItem()));
            rst = rec.GetPatientName(ID);
            PNameTxt.setText(rst.getString("PName"));
            ResultSet rs;
            Bill bill = new Bill();
            rs = bill.GetBillNumber(ID);
           BillNoTxt.setText(rs.getString("BillNumber"));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e+"PName Txt Error");
        }
        }
 
    }//GEN-LAST:event_PIDComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorGiveMedicineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorGiveMedicineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorGiveMedicineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorGiveMedicineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorGiveMedicineForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel BillNoTxt;
    private javax.swing.JCheckBox CheckOutChk;
    private javax.swing.JLabel DFieldTxt;
    private javax.swing.JLabel DateTxt;
    private javax.swing.JComboBox<String> DiseaseCombo;
    private javax.swing.JButton GeneratePresButton;
    private javax.swing.JComboBox<String> MedicineCombo;
    public javax.swing.JTextArea MedicinesGiven;
    private javax.swing.JComboBox<String> PIDCombo;
    private javax.swing.JLabel PNameTxt;
    private javax.swing.JButton PatientInfoButton;
    private javax.swing.JTextField QToGiveTxt;
    private javax.swing.JLabel QuantityAvailableTxt;
    private javax.swing.JButton SignOutButton;
    public javax.swing.JLabel TPriceTxt;
    private javax.swing.JLabel Txt;
    private javax.swing.JLabel UnitPriceTxt;
    private javax.swing.JButton UpcomingAppButton;
    private javax.swing.JLabel UserIDTxt;
    private javax.swing.JLabel UserNameTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
