
import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Muaaz
 */
public class LoginScreenForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public LoginScreenForm() {
        initComponents();
        this.setLocationRelativeTo(null); 
       GetUser();
    }
    public String GetUser(){
         String user = UserIDTxt.getText();
         return user;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UserIDTxt = new javax.swing.JTextField();
        PasswordTxt = new javax.swing.JPasswordField();
        LoginAsCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LoginSideBar1.PNG"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-120, 0, 490, 480);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(390, 270, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Login As:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(390, 80, 100, 30);

        UserIDTxt.setBackground(new java.awt.Color(102, 102, 102));
        UserIDTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UserIDTxt.setForeground(new java.awt.Color(255, 255, 255));
        UserIDTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                UserIDTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UserIDTxtKeyTyped(evt);
            }
        });
        jPanel1.add(UserIDTxt);
        UserIDTxt.setBounds(390, 200, 250, 30);

        PasswordTxt.setBackground(new java.awt.Color(102, 102, 102));
        PasswordTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PasswordTxt.setForeground(new java.awt.Color(255, 255, 255));
        PasswordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTxtActionPerformed(evt);
            }
        });
        PasswordTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PasswordTxtKeyReleased(evt);
            }
        });
        jPanel1.add(PasswordTxt);
        PasswordTxt.setBounds(390, 310, 250, 30);

        LoginAsCombo.setBackground(new java.awt.Color(102, 102, 102));
        LoginAsCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Receptionist", "Doctor" }));
        LoginAsCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginAsComboActionPerformed(evt);
            }
        });
        jPanel1.add(LoginAsCombo);
        LoginAsCombo.setBounds(390, 120, 250, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("User ID");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(390, 160, 100, 30);

        LoginButton.setBackground(new java.awt.Color(102, 102, 102));
        LoginButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login.png"))); // NOI18N
        LoginButton.setText("Login");
        LoginButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login.png"))); // NOI18N
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LoginButton);
        LoginButton.setBounds(390, 400, 130, 60);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(390, 240, 250, 14);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(390, 350, 250, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sadar", "airport", "nazimabad" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(390, 50, 250, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Branch");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(390, 20, 100, 17);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(540, 400, 120, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTxtActionPerformed

    private void LoginAsComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginAsComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginAsComboActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        try{
            
        if (UserIDTxt.getText().trim().isEmpty())
        {
            jLabel2.setText("Field Is Empty");
        }

        if(PasswordTxt.getText().trim().isEmpty())
        {
            jLabel6.setText("Field Is Empty");
        }
        String LoginAs=String.valueOf(LoginAsCombo.getSelectedItem());
        admin login = new admin();
        Patient p=new Patient();
        Receptionist re =new Receptionist();
        Doctor d=new Doctor();
        int ID = Integer.parseInt(UserIDTxt.getText());
        if(LoginAs.equals("Admin")){
        if(login.chkAdminPass(ID,PasswordTxt.getText())){
           AdminMainForm reg = new AdminMainForm(ID);
            reg.setVisible(true);
            this.setVisible(false);
            }
                  else{
                      JOptionPane.showMessageDialog(null, "Invalid UserID or Password");
                  }
        }
          
        else 
             if(LoginAs.equals("Doctor")){
                 if(d.chkpass(ID,PasswordTxt.getText())){
                admin chk = new admin(ID);
                DoctorMainForm dmain = new DoctorMainForm(ID);
          
          dmain.setVisible(true);
            this.setVisible(false);
            }
                 else{
                      JOptionPane.showMessageDialog(null, "Invalid UserID or Password");
                  }
        }
            
       else 
             if(LoginAs.equals("Receptionist")){
                 if(re.chkpass(ID,PasswordTxt.getText())){
          ReceptionistMainForm rmain = new ReceptionistMainForm(ID);
          rmain.setVisible(true);
            this.setVisible(false);
            }
                 else{
                      JOptionPane.showMessageDialog(null, "Invalid UserID or Password");
                  }
        }
        else{
            JOptionPane.showMessageDialog(null, "Invalid ID or Password");
        }}
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null, null);
        }
             
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void UserIDTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UserIDTxtKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!( Character.isDigit(c) || (c==KeyEvent.VK_BACKSPACE) || (c== KeyEvent.VK_DELETE))){
            evt.consume();
        }
    }//GEN-LAST:event_UserIDTxtKeyTyped

    private void UserIDTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UserIDTxtKeyReleased
        // TODO add your handling code here:
                 jLabel2.setText(" ");
        //id
    }//GEN-LAST:event_UserIDTxtKeyReleased

    private void PasswordTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordTxtKeyReleased
        // TODO add your handling code here:
        //pass
                 jLabel6.setText(" ");
    }//GEN-LAST:event_PasswordTxtKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreenForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreenForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreenForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreenForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreenForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> LoginAsCombo;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPasswordField PasswordTxt;
    private javax.swing.JTextField UserIDTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
