
import java.io.Console;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Muaaz
 */
public class PatientPayBill extends javax.swing.JFrame {

    /**
     * Creates new form PatientPayBill
     */

    public PatientPayBill() {
        initComponents();
            ResultSet rst;   
           this.setLocationRelativeTo(null);
          try {
            Bill bill = new Bill();
             rst =  bill.SelectBillNumber();
             while(rst.next()){
                 BillNumberCombo.addItem(rst.getString("BillNumber"));
             }
              
  } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, "PatientPayBill Error");
      }
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AmountTxt = new javax.swing.JTextField();
        TotalAmount = new javax.swing.JTextField();
        PayButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        BillNumberCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pay-your-bill.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 210, 190);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Amount To Pay");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 280, 150, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total Amount");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(180, 220, 150, 30);

        AmountTxt.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 14)); // NOI18N
        AmountTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmountTxtActionPerformed(evt);
            }
        });
        jPanel1.add(AmountTxt);
        AmountTxt.setBounds(360, 280, 170, 30);

        TotalAmount.setEditable(false);
        TotalAmount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(TotalAmount);
        TotalAmount.setBounds(360, 220, 170, 30);

        PayButton.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        PayButton.setText("PAY");
        PayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayButtonActionPerformed(evt);
            }
        });
        jPanel1.add(PayButton);
        PayButton.setBounds(270, 350, 130, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bill Number");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(180, 170, 150, 30);

        BillNumberCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Bill Number" }));
        BillNumberCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillNumberComboActionPerformed(evt);
            }
        });
        jPanel1.add(BillNumberCombo);
        BillNumberCombo.setBounds(360, 170, 170, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayButtonActionPerformed
        // TODO add your handling code here:
        if(AmountTxt.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Enter Amount To Pay");
            
        }
        else{
            PayButton.setEnabled(true);
              Bill bill = new Bill(Integer.parseInt(AmountTxt.getText()));
             bill.PayBill(Integer.parseInt(String.valueOf(BillNumberCombo.getSelectedItem())));
              AmountTxt.setText("");
                TotalAmount.setText("");
                BillNumberCombo.setSelectedItem("Select Bill Number");
                 this.setVisible(false);
        }
       
      
    }//GEN-LAST:event_PayButtonActionPerformed

    private void AmountTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmountTxtActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_AmountTxtActionPerformed

    private void BillNumberComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillNumberComboActionPerformed
        // TODO add your handling code here:
        if(BillNumberCombo.getSelectedItem().equals("Select Bill Number")){
            TotalAmount.setText("");
            AmountTxt.setText("");
        }
        else{
            
            try {
                ResultSet rst;
            Bill bill = new Bill();
           rst =  bill.SelectTotal(Integer.parseInt(String.valueOf(BillNumberCombo.getSelectedItem())));
                TotalAmount.setText(rst.getString("Total"));
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "BillNumberCombo Error");
            }
        }
    }//GEN-LAST:event_BillNumberComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientPayBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientPayBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientPayBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientPayBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientPayBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmountTxt;
    private javax.swing.JComboBox<String> BillNumberCombo;
    private javax.swing.JButton PayButton;
    private javax.swing.JTextField TotalAmount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
