
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Muaaz
 */
public class PatientMainForm extends javax.swing.JFrame {

    /**
     * Creates new form PatientMainForm
     */
    Date date = new Date();
    public PatientMainForm() {
       
    }
    public PatientMainForm(int ID){
        initComponents();
        this.setLocationRelativeTo(null);
        
            DateTxt.setText(date.toString());
           UserIDTxt.setText(String.valueOf(ID));
           Patient p=new Patient();
          try {
           ResultSet rst;
          rst = p.getname(Integer.parseInt(UserIDTxt.getText()));
         String Name = rst.getString("PName");
          UserNameTxt.setText(Name);
      } catch (SQLException ex) {
          
      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        SignOutButton = new javax.swing.JButton();
        ViewHistoryButton = new javax.swing.JButton();
        MakeAppointmentButton = new javax.swing.JButton();
        Txt = new javax.swing.JLabel();
        UserIDTxt = new javax.swing.JLabel();
        UserNameTxt = new javax.swing.JLabel();
        DateTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(null);

        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PatientMainBG.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 430);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(160, 90, 680, 440);

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255)));
        jPanel3.setLayout(null);

        SignOutButton.setText("Sign Out");
        SignOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignOutButtonActionPerformed(evt);
            }
        });
        jPanel3.add(SignOutButton);
        SignOutButton.setBounds(0, 210, 156, 39);

        ViewHistoryButton.setText("View History");
        ViewHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewHistoryButtonActionPerformed(evt);
            }
        });
        jPanel3.add(ViewHistoryButton);
        ViewHistoryButton.setBounds(0, 110, 156, 39);

        MakeAppointmentButton.setText("Make Appointment");
        MakeAppointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeAppointmentButtonActionPerformed(evt);
            }
        });
        jPanel3.add(MakeAppointmentButton);
        MakeAppointmentButton.setBounds(0, 60, 156, 39);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 90, 160, 440);

        Txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Txt.setForeground(new java.awt.Color(255, 255, 255));
        Txt.setText("LOGIN AS");
        Txt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        jPanel1.add(Txt);
        Txt.setBounds(10, 50, 90, 30);

        UserIDTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UserIDTxt.setForeground(new java.awt.Color(255, 255, 255));
        UserIDTxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        jPanel1.add(UserIDTxt);
        UserIDTxt.setBounds(100, 50, 80, 30);

        UserNameTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UserNameTxt.setForeground(new java.awt.Color(255, 255, 255));
        UserNameTxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        jPanel1.add(UserNameTxt);
        UserNameTxt.setBounds(180, 50, 120, 30);

        DateTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DateTxt.setForeground(new java.awt.Color(255, 255, 255));
        DateTxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        jPanel1.add(DateTxt);
        DateTxt.setBounds(530, 50, 260, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignOutButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        LoginScreenForm login = new LoginScreenForm();
        JOptionPane.showMessageDialog(null, "Logged Out");
        login.setVisible(true);
    }//GEN-LAST:event_SignOutButtonActionPerformed

    private void ViewHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewHistoryButtonActionPerformed
        // TODO add your handling code here:
        PatientVisitHistory his = new PatientVisitHistory(Integer.parseInt(UserIDTxt.getText()));
       // this.setVisible(false);
        his.setVisible(true);
        
    }//GEN-LAST:event_ViewHistoryButtonActionPerformed

    private void MakeAppointmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakeAppointmentButtonActionPerformed
        // TODO add your handling code here:
        Patient p = new Patient();
        p.ReCheckIn(Integer.parseInt(UserIDTxt.getText()));
    }//GEN-LAST:event_MakeAppointmentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateTxt;
    private javax.swing.JButton MakeAppointmentButton;
    private javax.swing.JButton SignOutButton;
    private javax.swing.JLabel Txt;
    private javax.swing.JLabel UserIDTxt;
    private javax.swing.JLabel UserNameTxt;
    private javax.swing.JButton ViewHistoryButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
