
import javax.swing.JOptionPane;
import com.sun.glass.events.KeyEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Muaaz
 */
public class RegPatient extends javax.swing.JFrame {

    /**
     * Creates new form SignUpForm
     */
    public RegPatient() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AgeTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        MobileTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        AddressTxt = new javax.swing.JTextField();
        FemaleChk = new javax.swing.JRadioButton();
        MaleChk = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        RegisterButton = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Register Patients");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(420, 40, 210, 40);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(370, 150, 90, 30);

        NameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(NameTxt);
        NameTxt.setBounds(480, 150, 170, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LoginSideBar1.PNG"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(-120, 0, 490, 510);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gender");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(370, 190, 90, 30);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Age");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(370, 230, 90, 30);

        AgeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeTxtActionPerformed(evt);
            }
        });
        AgeTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AgeTxtKeyTyped(evt);
            }
        });
        jPanel1.add(AgeTxt);
        AgeTxt.setBounds(480, 230, 170, 30);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mobile");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(370, 270, 90, 30);

        MobileTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobileTxtActionPerformed(evt);
            }
        });
        MobileTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MobileTxtKeyTyped(evt);
            }
        });
        jPanel1.add(MobileTxt);
        MobileTxt.setBounds(480, 270, 170, 30);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Address");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(370, 310, 90, 30);

        AddressTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressTxtActionPerformed(evt);
            }
        });
        jPanel1.add(AddressTxt);
        AddressTxt.setBounds(480, 310, 170, 30);

        FemaleChk.setBackground(new java.awt.Color(51, 51, 51));
        FemaleChk.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FemaleChk.setForeground(new java.awt.Color(255, 255, 255));
        FemaleChk.setText("Female");
        FemaleChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleChkActionPerformed(evt);
            }
        });
        jPanel1.add(FemaleChk);
        FemaleChk.setBounds(550, 190, 100, 30);

        MaleChk.setBackground(new java.awt.Color(51, 51, 51));
        MaleChk.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MaleChk.setForeground(new java.awt.Color(255, 255, 255));
        MaleChk.setText("Male");
        MaleChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleChkActionPerformed(evt);
            }
        });
        jPanel1.add(MaleChk);
        MaleChk.setBounds(480, 190, 60, 30);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(470, 410, 80, 40);

        RegisterButton.setText("Register");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RegisterButton);
        RegisterButton.setBounds(380, 410, 80, 40);

        jCheckBox1.setText("Check In");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(490, 360, 67, 23);

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(563, 410, 80, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Patient ID");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(370, 110, 80, 17);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(480, 100, 170, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTxtActionPerformed

    private void AgeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeTxtActionPerformed

    private void MobileTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobileTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MobileTxtActionPerformed

    private void AddressTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressTxtActionPerformed

    private void FemaleChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleChkActionPerformed
        // TODO add your handling code here:
        MaleChk.setSelected(false);
    }//GEN-LAST:event_FemaleChkActionPerformed

    private void MaleChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleChkActionPerformed
        // TODO add your handling code here:
        FemaleChk.setSelected(false);
    }//GEN-LAST:event_MaleChkActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
            String Gender,nam;
        String name = NameTxt.getText();
        if(MaleChk.isSelected()){
             Gender = MaleChk.getText();
        }
        else{
            Gender = FemaleChk.getText();
        }
        int age = Integer.parseInt(AgeTxt.getText());
        String mobile = MobileTxt.getText();
        String address = AddressTxt.getText();
        nam = jCheckBox1.getText();
        Patient patient = new Patient(name, Gender, age, mobile, address,nam);
        patient.addPatient();
        patient.New_Patient_Id(name);
        
        NameTxt.setText("");
        AgeTxt.setText("");
        NameTxt.setText("");
        MobileTxt.setText("");
        AddressTxt.setText("");        
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ReceptionistMainForm screen = new ReceptionistMainForm();
        this.setVisible(false);
        screen.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AgeTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AgeTxtKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if (!( Character.isDigit(c) || (c==KeyEvent.VK_BACKSPACE) || (c== KeyEvent.VK_DELETE))){
            evt.consume();
        }
    }//GEN-LAST:event_AgeTxtKeyTyped

    private void MobileTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MobileTxtKeyTyped
        // TODO add your handling code here:
          char c = evt.getKeyChar();
        if (!( Character.isDigit(c) || (c==KeyEvent.VK_BACKSPACE) || (c== KeyEvent.VK_DELETE))){
            evt.consume();
        }
    }//GEN-LAST:event_MobileTxtKeyTyped

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String Gender;
        int s = Integer.parseInt(jTextField1.getText());  
        String name = NameTxt.getText();
        if(MaleChk.isSelected()){
             Gender = MaleChk.getText();
        }
        else{
            Gender = FemaleChk.getText();
        }
        int age = Integer.parseInt(AgeTxt.getText());
        String mobile = MobileTxt.getText();
        String address = AddressTxt.getText();
        String  nam = jCheckBox1.getText();
        Patient d1 = new Patient();
        d1.updatePatient(s);
        jTextField1.setText("");
        NameTxt.setText("");
        AgeTxt.setText("");
        NameTxt.setText("");
        MobileTxt.setText("");
        AddressTxt.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTxt;
    private javax.swing.JTextField AgeTxt;
    private javax.swing.JRadioButton FemaleChk;
    private javax.swing.JRadioButton MaleChk;
    private javax.swing.JTextField MobileTxt;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
